{% set version = "2.0.12" %}

package:
  name: bob.db.wine
  version: {{ version }}

source:
  fn: bob.db.wine-{{ version }}.zip
  md5: ff2ff9241006331ce91f8f72ef0f2efa
  url: https://pypi.io/packages/source/b/bob.db.wine/bob.db.wine-{{ version }}.zip

build:
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.db.base

  run:
    - python
    - bob.db.base

test:
  commands:
    - nosetests -sv bob.db.wine

  imports:
    - bob
    - bob.db
    - bob.db.wine

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Wine Database for bob

extra:
  recipe-maintainers:
    - 183amir
